"""added price field to room booking

Revision ID: 1eeec3b5f961
Revises: ec570e265938
Create Date: 2022-01-24 17:14:25.491397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eeec3b5f961'
down_revision = 'ec570e265938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'price')
    # ### end Alembic commands ###
