"""added start and end field

Revision ID: 48d592fbfd19
Revises: a868dbe70a64
Create Date: 2021-10-23 12:54:38.436007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d592fbfd19'
down_revision = 'a868dbe70a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_at', sa.Time(), nullable=True))
    op.add_column('bookings', sa.Column('end_at', sa.Time(), nullable=True))
    op.drop_column('bookings', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('duration', sa.INTEGER(), nullable=False))
    op.drop_column('bookings', 'end_at')
    op.drop_column('bookings', 'start_at')
    # ### end Alembic commands ###
