"""new letter table

Revision ID: eb1436de39a6
Revises: 48d592fbfd19
Create Date: 2022-01-24 11:32:22.266240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1436de39a6'
down_revision = '48d592fbfd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipent', sa.String(length=256), nullable=False),
    sa.Column('sender_01', sa.String(length=256), nullable=False),
    sa.Column('sender_02', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail')
    # ### end Alembic commands ###
