"""changes to mail table

Revision ID: ec570e265938
Revises: eb1436de39a6
Create Date: 2022-01-24 11:56:59.082084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec570e265938'
down_revision = 'eb1436de39a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail', sa.Column('sender_1', sa.String(length=256), nullable=False))
    op.add_column('mail', sa.Column('sender_2', sa.String(length=256), nullable=True))
    op.drop_column('mail', 'sender_01')
    op.drop_column('mail', 'sender_02')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mail', sa.Column('sender_02', sa.VARCHAR(length=256), nullable=True))
    op.add_column('mail', sa.Column('sender_01', sa.VARCHAR(length=256), nullable=False))
    op.drop_column('mail', 'sender_2')
    op.drop_column('mail', 'sender_1')
    # ### end Alembic commands ###
